version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - '4173:4173'
    volumes:
      - .:/app
      - /app/node_modules # Ensure fresh dependencies inside container
    command: ['npm', 'run', 'preview', '--', '--port', '4173']
    networks:
      - vite-network

networks:
  vite-network:
    driver: bridge
